"""create tablssdsfde

Revision ID: 481f5396a2ab
Revises: 3a3a34cd4f78
Create Date: 2025-10-25 17:13:41.462112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481f5396a2ab'
down_revision: Union[str, Sequence[str], None] = '3a3a34cd4f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
